version: '2'

services:
  directory.walker:
    image: directory_walker
    container_name: directory_walker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DIRECTORYWALKER_OS=Linux 
    ports:
      - "8080:80"
    volumes: 
      - /var/log/DirectoryWalker:/var/log/DirectoryWalker 
    restart: always 
    network_mode: "bridge"